### ISSUE TITLE
inherited-members doesn't support instance attributes on super class

### ISSUE THREAD

**Issue by jason-bentley** [BCG-Gamma/pytools#127]
**Describe the bug**
The inherited-members doesn't support instance attributes on super class when generating sphinx documentation.
Fix appears to be on the way see here: https://github.com/sphinx-doc/sphinx/pull/8587 so an update to Sphinx 3.5 once stable should hopefully resolve the issue.

**To Reproduce**
Create documentation using `python make.py html` and view `DEFAULT_STYLE` in the attribute summary for `pytools.vz.Drawer` vs `pytools.viz.dendrogram` and see that only one is described.

**Expected behavior**
In all places where `DEFAULT_STYLE` is shown in an attribute summary the description should be present.

**Screenshots**
![image](https://user-images.githubusercontent.com/17013354/104042877-ee6c7780-51d2-11eb-8362-5c38812ef938.png)
![image](https://user-images.githubusercontent.com/17013354/104042995-1360ea80-51d3-11eb-8ac9-bab6eab3fb12.png)

**Comment by j-ittner** [comment]
Addressed using sphinx 4.5
